- name: Add a new user named lukas
  user:
          name=lukas
          password={{ lukas_password | password_hash('sha512') }}

- name: Add lukas user to the sudoers
  copy:
        dest: "/etc/sudoers.d/lukas"
        content: "lukas  ALL=(ALL)  NOPASSWD: ALL"
 
- name: Deploy SSH Key
  authorized_key: user=lukas
                     key="{{ lookup('file', '/Users/lukasball/.ssh/id_rsa.pub') }}"
                     state=present
 
- name: Disable Password Authentication
  lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
  notify:
       - restart ssh
 
- name: Disable Root Login
  lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
  notify:
       - restart ssh
